-- V7: Add profile photo and verification fields
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS profile_photo_url VARCHAR(500);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
